### ISSUE TITLE
CSS should be built into dist bundle directly

### ISSUE THREAD

**Issue by brennancheung** [firebase/firebaseui-web-react#10]
I ran into an issue while trying to use this library.  Basically it failed to import the `firebaseui.css` because it is common to configure webpack with the following:

      {
        test: /\.css/,
        exclude: /node_modules/,
        use: ['style-loader', 'css-loader']
      }

The `exclude` prevents the CSS file in `node_modules` from being processed.

Excluding `node_modules` is a normal convention used to prevent slow build times.  It is normally expected that any `npm` module already be built with everything it needs.

I worked around it by removing the `exclude` but it should probably work without requiring this.

Is it possible to build the CSS directly into the `dist` bundle to avoid this problem?

**Comment by sheats** [comment]
I just hit this issue too... makes it a pain to use this library.

**Comment by nicolasgarnier** [comment]
+1 I'll try to build a version of the lib that includes the CSS in a style tag for simplicity.

**Comment by nicolasgarnier** [comment]
I just added a component which includes the CSS. If you use `StyledFirebaseAuth` rather than `FirebaseAuth` the CSS is already incorporated in the component and there is no need to use CSS loaders.

Please use the lates version (v1.1.0) and refer to the README for instructions.

Actually using this makes sense since generating a separate CSS is useful for Server-Side Rendering but this library does not support SSR (since the underlying library does not work ServerSide)
