### ISSUE TITLE
Firebase service named 'auth' already registered

### ISSUE THREAD

**Issue by vassiliskrikonis** [firebase/firebaseui-web-react#15]
I'm following the example on a fresh create-react-app app. It only worked on the first time. From then it displays the following error 

    Firebase: Firebase service named 'auth' already registered (app/duplicate-service).

**Comment by nicolasgarnier** [comment]
It looks like you may be initializing Firebase multiple times. For instance if you are calling `firebase.initializeApp(...)` more than once (or in more than one file.

By the way we just released a new version and new samples. Let me know if you still have the issue with the new samples.

**Comment by Superpencil** [comment]
Same here; on a fresh `create-react-app` the provided example does not seem to work, apart from the error mentioned above there is another one that I think might be the culprit: ```TypeError: this.unregisterAuthObserver is not a function. (In 'this.unregisterAuthObserver()', 'this.unregisterAuthObserver' is undefined)```

**Comment by Superpencil** [comment]
Same here; on a fresh `create-react-app` the provided example does not seem to work, apart from the error mentioned above there is another one that I think might be the culprit: 
```
TypeError: this.unregisterAuthObserver is not a function. (In 'this.unregisterAuthObserver()', 'this.unregisterAuthObserver' is undefined)
```

@nicolasgarnier might this be due to the Webpack configuration that `create-react-app` ships with?

**Comment by nicolasgarnier** [comment]
It might very well be due to some webpack config generated by `create-react-app`. At least I'm not able to replicate these issues with the webpack config in the example.

Normally the error `Firebase: Firebase service named 'auth' already registered (app/duplicate-service).` should happen if `firebase/auth` is imported multiple times, for instance `firebase/auth` is already backed in `firebase` and also `angularfire`. See this answer: https://github.com/firebase/firebaseui-web/issues/11

But normally, at least for double imports of `firebase` vs `firebase/app` webpack resolves the duplicates.

@Superpencil Are you using any other library that might invlude firebase already (like angularfire?) Could you upload your project somewhere so I could replicate the issue please? :)
