### ISSUE TITLE
Styledfirebaseui don't know my initializaion 

### ISSUE THREAD

**Issue by thanhtutzaw** [firebase/firebaseui-web-react#177]
I called **styledfirebaseui**  in   **my firebase-auth component**.
That component knows my Firebase initalize and   Styledfirebaseui  don't know . 
But when I initalize again **it says This is duplicate**.
### This successfully work with Firebase v8

**Current Version**

- Firebase v9.9

![Screenshot (1123)](https://user-images.githubusercontent.com/71011043/178903490-64559f47-c662-4e09-a99b-7cb4f18c473e.png)
![Screenshot (1126)](https://user-images.githubusercontent.com/71011043/178903505-b9b9ba4b-92c0-4593-97d0-6eef0bb7e0c4.png)

**Comment by siroccomask** [comment]
I believe your issue is that you are mixing v8 and v0 implementations. `firebase.initializeApp(...)` is the v8 way of doing initialize and `getAuth` is v9 (previously `firebase.auth()`)

In the second example, you want to import initializeApp from firebase version 9 like so: 
`import { initializeApp } from 'firebase/app';`=
Then use it like
`const app = initializeApp(config);`
Then in v9, you export app instead of firebase
`export default app;`

Then, in the components that use auth you use 
`const auth = getAuth(app)`

**Comment by thanhtutzaw** [comment]
Yeah I changed code like this . And it works
`import { getAuth } from 'firebase/auth';`
` <StyledFirebaseAuth
            firebaseAuth={getAuth()}
          />`
