### ISSUE TITLE
Support credentialHelper setting

### ISSUE THREAD

**Issue by kmjennison** [firebase/firebaseui-web-react#2]
It looks like this does not support the Firebase UI `credentialHelper` config setting. I set `credentialHelper: 'firebaseui.auth.CredentialHelper.NONE'` and email sign-in still opens accountchooser.com.

**Comment by nicolasgarnier** [comment]
It's strange since we just pass the `uiConfig` object untouched to the underlying firebaseUi widget since firebaseui-web-react is just a wrapper ([see code](https://github.com/firebase/firebaseui-web-react/blob/master/src/FirebaseAuth.jsx#L53)). 

Have you tested to see if this works when using firebaseui-web directly?

**Comment by kmjennison** [comment]
Never mind, this was user error 😄 I had a typo in the property value, and `firebaseui-web` defaults to the account chooser for any value other than 'none'.
