### ISSUE TITLE
Support for firebase 6.x.x

### ISSUE THREAD

**Issue by nodkrot** [firebase/firebaseui-web-react#74]
I've tested this with firebase 6.3.1 with my app, everything seems to work. Are there plans to update package.json peer dependencies?

**Comment by jhuleatt** [comment]
Thanks @nodkrot! I'm working on a PR now.

We're also way behind on the firebaseui dependency. They moved to [4.x back in May](https://github.com/firebase/firebaseui-web/releases/tag/v4.0.0). The problem is that 4.x is not backwards compatible with the Firebase 5.x SDK.

Does anyone have strong opinions against this repo dropping support for Firebase 5.x? It would let us stay up to date with [firebaseui-web](https://github.com/firebase/firebaseui-web).

**Comment by nodkrot** [comment]
That’s great, dropping shouldn’t be a problem since people can still install current version in the future. Am I missing anything?

**Comment by jhuleatt** [comment]
Good point! I'll release this as 4.0.0 since we're breaking backwards compatibility

**Comment by jhuleatt** [comment]
Released 4.0.0!

**Comment by nodkrot** [comment]
Awesome, I will test it out.
